name: fisrt workflows

on:
  push:
    branches:
      - main

jobs:
   job1:
     runs-on: ubuntu-latest
     steps:
     - run: pwd
     - run: ls
   job2:
     runs-on: windows-latest
     steps:
     - run: dir